# .github/workflows/daily-post.yml
name: Daily Bluesky Post

on:
  schedule:
    - cron: '0 9 * * *'  # Runs at 9:00 AM UTC every day
  workflow_dispatch:      # Allows manual trigger

jobs:
  post:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install atproto python-dotenv requests beautifulsoup4
        
    - name: Create .env file
      run: |
        echo "BLUESKY_USERNAME=${{ secrets.BLUESKY_USERNAME }}" > .env
        echo "BLUESKY_PASSWORD=${{ secrets.BLUESKY_PASSWORD }}" >> .env
      
    - name: Run script
      run: python main.py
